export const FORMULARIO_PARTIDO ='FORMULARIO_PARTIDO';
export const OBTENER_PARTIDO ='OBTENER_PARTIDO';
export const AGREGAR_PROYECTO='AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO='VALIDAR_FORMULARIO';
export const PARTIDO_ACTUAL='PARTIDO_ACTUAL';
export const ELIMINAR_PARTIDO='ELIMINAR_PARTIDO';
export const PARTIDO_ERROR ='PARTIDO_ERROR';


export const DATOS_PARTIDO='DATOS_PARTIDO';
export const AGREGAR_DATOS ='AGREGAR_DATOS'
export const VALIDAR_DATO='VALIDAR_DATO';
export const ELIMINAR_DATOS ="ELIMINAR_DATOS"

export const DATO_ACTUAL ="DATO_ACTUAL"
export const ACTUALIZAR_DATO ="ACTUALIZAR_DATO"
export const LIMPIAR_DATO ='LIMPIAR_DATO'

export const MOSTRA_ALERTA ='MOSTRA_ALERTA'
export const OCULTAR_ALERTA ='OCULTAR_ALERTA'


export const REGISTRO_EXITOSO ='REGISTRO_EXITOSO ';
export const REGISTRO_ERROR ='REGISTRO_ERROR';
export const OBTENER_USUARIO='OBTENER_USUARIO';
export const LOGIN_EXITOSO='LOGIN_EXITOSO';
export const LOGIN_ERROR='LOGIN_ERROR';
export const CERRAR_SESION='CERRAR_SESION';


 


